# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

react_native_path = '../node_modules/react-native'

target 'CERNPhoneApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CERNPhoneApp
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'

  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'RNCallKeep', :path => '../node_modules/react-native-callkeep'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

  target 'CERNPhoneAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CERNPhoneApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CERNPhoneApp-tvOS

  target 'CERNPhoneApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
