parser: babel-eslint
extends:
  - airbnb
  - prettier
  - plugin:prettier/recommended
  - prettier/babel
  - prettier/react
plugins:
  - prettier
  - react
  - jsx-a11y
  - import
env:
  node: true
rules:
  prettier/prettier: error
  react/jsx-filename-extension: off
  react/prop-types:
    - error
    - ignore: [navigation]
